[{
    "user_name":"murali",
    "date":ISODate("2020-10-16"),
    "attendance":"present",
    "task_submission":"passes"
},
{
    "user_name":"indhuja",
    "date":ISODate("2020-10-20"),
    "attendance":"absent",
    "task_submission":"passes"
},
{
    "user_name":"sobiya",
    "date":ISODate("2020-10-29"),
    "attendance":"present",
    "task_submission":"failed"
},
{
    "user_name":"deva",
    "date":ISODate("2020-11-01"),
    "attendance":"absent",
    "task_submission":"passed"
},
{
    "user_name":"vignesh",
    "date":ISODate("2020-11-16"),
    "attendance":"present",
    "task_submission":"failed"
},
{
    "user_name":"rani",
    "date":ISODate("2020-11-17"),
    "attendance":"present",
    "task_submission":"passed"
}]